Implement logical types
bornfight/avro-to-typescript pull request #23
Opened 2019-01-25 15:38 UTC by ivank

Hello @Dvorsky, 10x a lot for this awesome project!
I was evaluating using it and it turns out it does not support [Avro Logical Types](https://avro.apache.org/docs/1.8.0/spec.html#Logical+Types) Which we use heavily. 

With this PR it parses all the logical types we use successfully. I've tried to use your style to the best of my ability, hopefully I've not made the change too big. Can you take a look and see if we it works for you?

2019-01-28 09:13 UTC, dvorsky requested changes
Hi @ivank, thanks for contributing! I took a look at the PR and everything seems fine. I would just like to ask you to update readme with support for logical types and maybe an example of how new CLI usage would look like? Thanks again for this nice contribution 😄

2019-01-28 15:00 UTC, ivank commented
Hey @Dvorsky 10x for the quick response.
Here you go I hope thats ok, sorry for missing out on the README.md, completely slipped my mind :)

2019-01-28 15:01 UTC, ivank commented on README.md
> +If there are logical types in avro schema but you don't provide a mapping for them, they will default to the underlying primitive type.
```suggestion
If there are logical types in the avro schema but you don't provide a mapping for them, they will default to the underlying primitive type.
```

2019-01-30 11:43 UTC, dvorsky approved these changes

2019-01-30 11:43 UTC, Dvorsky commented
All good! Will merge and publish on npm new version.

2019-01-30 11:44 UTC, merged